### ISSUE TITLE
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

### ISSUE THREAD

**Issue by dangz90** [shubhamchaudhary/aesthetics#2]
Hi,

I was generating the GMM with a list of images and then I received the following error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
../images4AVA/images
  File "C:\Users\dangz\Anaconda3\lib\multiprocessing\spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\dangz\Anaconda3\lib\multiprocessing\spawn.py", line 115, in _main
    prepare(preparation_data)
  File "C:\Users\dangz\Anaconda3\lib\multiprocessing\spawn.py", line 226, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\dangz\Anaconda3\lib\multiprocessing\spawn.py", line 278, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\dangz\Anaconda3\lib\runpy.py", line 240, in run_path
['../images4AVA/images\\1000.jpg', '../images4AVA/images\\10000.jpg', '../images4AVA/images\\10002.jpg', '../images4AVA/images\\10003.jpg', '../images4AVA/images\\10005.jpg', '../images4AVA/images\\100050.jpg', '../images4AVA/images\\10006.jpg', '../images4AVA/images\\10007.jpg', '../images4AVA/images\\10008.jpg', '../images4AVA/images\\100082.jpg']
../images4AVA/images
['../images4AVA/images\\1000.jpg', '../images4AVA/images\\10000.jpg', '../images4AVA/images\\10002.jpg', '../images4AVA/images\\10003.jpg', '../images4AVA/images\\10005.jpg', '../images4AVA/images\\100050.jpg', '../images4AVA/images\\10006.jpg', '../images4AVA/images\\10007.jpg', '../images4AVA/images\\10008.jpg', '../images4AVA/images\\100082.jpg']
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\dangz\Anaconda3\lib\multiprocessing\spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\dangz\Anaconda3\lib\multiprocessing\spawn.py", line 115, in _main
    prepare(preparation_data)
  File "C:\Users\dangz\Anaconda3\lib\multiprocessing\spawn.py", line 226, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\dangz\Anaconda3\lib\multiprocessing\spawn.py", line 278, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\dangz\Anaconda3\lib\runpy.py", line 240, in run_path
    exitcode = _main(fd)
  File "C:\Users\dangz\Anaconda3\lib\multiprocessing\spawn.py", line 115, in _main
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    prepare(preparation_data)
  File "C:\Users\dangz\Anaconda3\lib\multiprocessing\spawn.py", line 226, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\dangz\Anaconda3\lib\multiprocessing\spawn.py", line 278, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\dangz\Anaconda3\lib\runpy.py", line 240, in run_path
  File "C:\Users\dangz\Anaconda3\lib\multiprocessing\spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\dangz\Anaconda3\lib\multiprocessing\spawn.py", line 115, in _main
    prepare(preparation_data)
  File "C:\Users\dangz\Anaconda3\lib\multiprocessing\spawn.py", line 226, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\dangz\Anaconda3\lib\multiprocessing\spawn.py", line 278, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\dangz\Anaconda3\lib\runpy.py", line 240, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\dangz\Anaconda3\lib\runpy.py", line 96, in _run_module_code
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\dangz\Anaconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\dangz\Anaconda3\lib\runpy.py", line 85, in _run_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\dangz\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\dangz\Documents\Fotolog\Aesthetic\descriptor\descriptors_aesthetics.py", line 34, in <module>
    gaussian_mm = gmmClass.generate('../images4AVA/images', 10)
  File "C:\Users\dangz\Documents\Fotolog\Aesthetic\descriptor\aesthetics\fisher\gmm.py", line 42, in generate
    img_descriptors = [descriptor.folder(folder, limit) for folder in sorted(glob.glob(input_folder))]
      File "C:\Users\dangz\Documents\Fotolog\Aesthetic\descriptor\aesthetics\fisher\gmm.py", line 42, in <listcomp>
pkg_name=pkg_name, script_name=fname)
  File "C:\Users\dangz\Anaconda3\lib\runpy.py", line 96, in _run_module_code
    img_descriptors = [descriptor.folder(folder, limit) for folder in sorted(glob.glob(input_folder))]
  File "C:\Users\dangz\Documents\Fotolog\Aesthetic\descriptor\aesthetics\fisher\descriptors.py", line 36, in folder
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\dangz\Anaconda3\lib\runpy.py", line 85, in _run_code
    futures = executor.map(self.image_file, files)
  File "C:\Users\dangz\Anaconda3\lib\concurrent\futures\process.py", line 484, in map
    exec(code, run_globals)
  File "C:\Users\dangz\Documents\Fotolog\Aesthetic\descriptor\descriptors_aesthetics.py", line 34, in <module>
    gaussian_mm = gmmClass.generate('../images4AVA/images', 10)
  File "C:\Users\dangz\Documents\Fotolog\Aesthetic\descriptor\aesthetics\fisher\gmm.py", line 42, in generate
        exec(code, run_globals)
  File "C:\Users\dangz\Documents\Fotolog\Aesthetic\descriptor\descriptors_aesthetics.py", line 34, in <module>
        gaussian_mm = gmmClass.generate('../images4AVA/images', 10)
  File "C:\Users\dangz\Documents\Fotolog\Aesthetic\descriptor\aesthetics\fisher\gmm.py", line 42, in generate
pkg_name=pkg_name, script_name=fname)
  File "C:\Users\dangz\Anaconda3\lib\runpy.py", line 96, in _run_module_code
    img_descriptors = [descriptor.folder(folder, limit) for folder in sorted(glob.glob(input_folder))]
  File "C:\Users\dangz\Documents\Fotolog\Aesthetic\descriptor\aesthetics\fisher\gmm.py", line 42, in <listcomp>
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\dangz\Anaconda3\lib\runpy.py", line 85, in _run_code
    img_descriptors = [descriptor.folder(folder, limit) for folder in sorted(glob.glob(input_folder))]
  File "C:\Users\dangz\Documents\Fotolog\Aesthetic\descriptor\aesthetics\fisher\descriptors.py", line 36, in folder
    exec(code, run_globals)
  File "C:\Users\dangz\Documents\Fotolog\Aesthetic\descriptor\descriptors_aesthetics.py", line 34, in <module>
    futures = executor.map(self.image_file, files)
  File "C:\Users\dangz\Anaconda3\lib\concurrent\futures\process.py", line 484, in map
    gaussian_mm = gmmClass.generate('../images4AVA/images', 10)
  File "C:\Users\dangz\Documents\Fotolog\Aesthetic\descriptor\aesthetics\fisher\gmm.py", line 42, in generate
    img_descriptors = [descriptor.folder(folder, limit) for folder in sorted(glob.glob(input_folder))]
  File "C:\Users\dangz\Documents\Fotolog\Aesthetic\descriptor\aesthetics\fisher\gmm.py", line 42, in <listcomp>
    img_descriptors = [descriptor.folder(folder, limit) for folder in sorted(glob.glob(input_folder))]
  File "C:\Users\dangz\Documents\Fotolog\Aesthetic\descriptor\aesthetics\fisher\descriptors.py", line 36, in folder
img_descriptors = [descriptor.folder(folder, limit) for folder in sorted(glob.glob(input_folder))]
    futures = executor.map(self.image_file, files)
  File "C:\Users\dangz\Anaconda3\lib\concurrent\futures\process.py", line 484, in map
  File "C:\Users\dangz\Documents\Fotolog\Aesthetic\descriptor\aesthetics\fisher\gmm.py", line 42, in <listcomp>
    img_descriptors = [descriptor.folder(folder, limit) for folder in sorted(glob.glob(input_folder))]
  File "C:\Users\dangz\Documents\Fotolog\Aesthetic\descriptor\aesthetics\fisher\descriptors.py", line 36, in folder
    futures = executor.map(self.image_file, files)
  File "C:\Users\dangz\Anaconda3\lib\concurrent\futures\process.py", line 484, in map
        timeout=timeout)timeout=timeout)
    timeout=timeout)  File "C:\Users\dangz\Anaconda3\lib\concurrent\futures\_base.py", line 548, in map

  File "C:\Users\dangz\Anaconda3\lib\concurrent\futures\_base.py", line 548, in map

  File "C:\Users\dangz\Anaconda3\lib\concurrent\futures\_base.py", line 548, in map
    timeout=timeout)
  File "C:\Users\dangz\Anaconda3\lib\concurrent\futures\_base.py", line 548, in map
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "C:\Users\dangz\Anaconda3\lib\concurrent\futures\_base.py", line 548, in <listcomp>
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "C:\Users\dangz\Anaconda3\lib\concurrent\futures\_base.py", line 548, in <listcomp>
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "C:\Users\dangz\Anaconda3\lib\concurrent\futures\process.py", line 454, in submit
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "C:\Users\dangz\Anaconda3\lib\concurrent\futures\process.py", line 454, in submit
    self._start_queue_management_thread()
  File "C:\Users\dangz\Anaconda3\lib\concurrent\futures\process.py", line 415, in _start_queue_management_thread
        self._adjust_process_count()
self._start_queue_management_thread()  File "C:\Users\dangz\Anaconda3\lib\concurrent\futures\process.py", line 434, in _adjust_process_count

  File "C:\Users\dangz\Anaconda3\lib\concurrent\futures\process.py", line 415, in _start_queue_management_thread
        self._adjust_process_count()p.start()

  File "C:\Users\dangz\Anaconda3\lib\multiprocessing\process.py", line 105, in start
  File "C:\Users\dangz\Anaconda3\lib\concurrent\futures\process.py", line 434, in _adjust_process_count
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "C:\Users\dangz\Anaconda3\lib\concurrent\futures\_base.py", line 548, in <listcomp>
    p.start()
  File "C:\Users\dangz\Anaconda3\lib\multiprocessing\process.py", line 105, in start
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "C:\Users\dangz\Anaconda3\lib\concurrent\futures\process.py", line 454, in submit
    self._start_queue_management_thread()
  File "C:\Users\dangz\Anaconda3\lib\concurrent\futures\process.py", line 415, in _start_queue_management_thread
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "C:\Users\dangz\Anaconda3\lib\concurrent\futures\_base.py", line 548, in <listcomp>
    self._adjust_process_count()
  File "C:\Users\dangz\Anaconda3\lib\concurrent\futures\process.py", line 434, in _adjust_process_count
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "C:\Users\dangz\Anaconda3\lib\concurrent\futures\process.py", line 454, in submit
    p.start()
  File "C:\Users\dangz\Anaconda3\lib\multiprocessing\process.py", line 105, in start
    self._start_queue_management_thread()
  File "C:\Users\dangz\Anaconda3\lib\concurrent\futures\process.py", line 415, in _start_queue_management_thread
    self._adjust_process_count()
  File "C:\Users\dangz\Anaconda3\lib\concurrent\futures\process.py", line 434, in _adjust_process_count
    p.start()
  File "C:\Users\dangz\Anaconda3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\dangz\Anaconda3\lib\multiprocessing\context.py", line 212, in _Popen
    self._popen = self._Popen(self)
  File "C:\Users\dangz\Anaconda3\lib\multiprocessing\context.py", line 212, in _Popen
    self._popen = self._Popen(self)
  File "C:\Users\dangz\Anaconda3\lib\multiprocessing\context.py", line 212, in _Popen
    self._popen = self._Popen(self)
  File "C:\Users\dangz\Anaconda3\lib\multiprocessing\context.py", line 212, in _Popen
        return _default_context.get_context().Process._Popen(process_obj)return _default_context.get_context().Process._Popen(process_obj)

  File "C:\Users\dangz\Anaconda3\lib\multiprocessing\context.py", line 313, in _Popen
  File "C:\Users\dangz\Anaconda3\lib\multiprocessing\context.py", line 313, in _Popen
        return Popen(process_obj)return Popen(process_obj)

  File "C:\Users\dangz\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 34, in __init__
  File "C:\Users\dangz\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 34, in __init__
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\dangz\Anaconda3\lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "C:\Users\dangz\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 34, in __init__
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\dangz\Anaconda3\lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "C:\Users\dangz\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 34, in __init__
        prep_data = spawn.get_preparation_data(process_obj._name)    
prep_data = spawn.get_preparation_data(process_obj._name)  File "C:\Users\dangz\Anaconda3\lib\multiprocessing\spawn.py", line 144, in get_preparation_data

  File "C:\Users\dangz\Anaconda3\lib\multiprocessing\spawn.py", line 144, in get_preparation_data
prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\dangz\Anaconda3\lib\multiprocessing\spawn.py", line 144, in get_preparation_data
        _check_not_importing_main()_check_not_importing_main()

  File "C:\Users\dangz\Anaconda3\lib\multiprocessing\spawn.py", line 137, in _check_not_importing_main
  File "C:\Users\dangz\Anaconda3\lib\multiprocessing\spawn.py", line 137, in _check_not_importing_main
        _check_not_importing_main()is not going to be frozen to produce an executable.''')

RuntimeError    : is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
  File "C:\Users\dangz\Anaconda3\lib\multiprocessing\spawn.py", line 137, in _check_not_importing_main

        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\dangz\Anaconda3\lib\multiprocessing\spawn.py", line 144, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\dangz\Anaconda3\lib\multiprocessing\spawn.py", line 137, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\dangz\Anaconda3\lib\threading.py", line 923, in _bootstrap_inner
    self.run()
  File "C:\Users\dangz\Anaconda3\lib\threading.py", line 871, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\dangz\Anaconda3\lib\concurrent\futures\process.py", line 295, in _queue_management_worker
    shutdown_worker()
  File "C:\Users\dangz\Anaconda3\lib\concurrent\futures\process.py", line 253, in shutdown_worker
    call_queue.put_nowait(None)
  File "C:\Users\dangz\Anaconda3\lib\multiprocessing\queues.py", line 129, in put_nowait
    return self.put(obj, False)
  File "C:\Users\dangz\Anaconda3\lib\multiprocessing\queues.py", line 83, in put
    raise Full
queue.Full

Traceback (most recent call last):
  File "C:\Users\dangz\Documents\Fotolog\Aesthetic\descriptor\descriptors_aesthetics.py", line 34, in <module>
    gaussian_mm = gmmClass.generate('../images4AVA/images', 10)
  File "C:\Users\dangz\Documents\Fotolog\Aesthetic\descriptor\aesthetics\fisher\gmm.py", line 42, in generate
    img_descriptors = [descriptor.folder(folder, limit) for folder in sorted(glob.glob(input_folder))]
  File "C:\Users\dangz\Documents\Fotolog\Aesthetic\descriptor\aesthetics\fisher\gmm.py", line 42, in <listcomp>
    img_descriptors = [descriptor.folder(folder, limit) for folder in sorted(glob.glob(input_folder))]
  File "C:\Users\dangz\Documents\Fotolog\Aesthetic\descriptor\aesthetics\fisher\descriptors.py", line 38, in folder
    descriptors = [f for f in futures]
  File "C:\Users\dangz\Documents\Fotolog\Aesthetic\descriptor\aesthetics\fisher\descriptors.py", line 38, in <listcomp>
    descriptors = [f for f in futures]
  File "C:\Users\dangz\Anaconda3\lib\site-packages\tqdm\_tqdm.py", line 862, in __iter__
    for obj in iterable:
  File "C:\Users\dangz\Anaconda3\lib\concurrent\futures\_base.py", line 556, in result_iterator
    yield future.result()
  File "C:\Users\dangz\Anaconda3\lib\concurrent\futures\_base.py", line 405, in result
    return self.__get_result()
  File "C:\Users\dangz\Anaconda3\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```

**Comment by dangz90** [comment]
Solved it by using protecting the main code:
if __name__ == '__main__':
